### ISSUE TITLE
ADD JS file in Guessing game

### ISSUE THREAD

**Issue by theExpertOrg** [theExpertOrg/Project_Expert#1]
**Add** correct Java script file to make the project work fluently in Guessing game

**Comment by ghost** [comment]
Can i do this .... please assign this issue to me.
I will write the complete code of JS to make to project complete

**Comment by theExpertOrg** [comment]
okay. 
I will assign this issue to @ajayexists  .
make sure that the game work properly

**Comment by ajayfounds** [comment]
please assign this to me

**Comment by theExpertOrg** [comment]
i assign this to @ajayfounds
