### ISSUE TITLE
ADD JS file in To-do Manager

### ISSUE THREAD

**Issue by theExpertOrg** [theExpertOrg/Project_Expert#2]
**add** the correct javascript file in the to-do manager folder.

**Comment by sulavghimiree** [comment]
Please assign me this. @theExpertOrg

**Comment by ghost** [comment]
@theExpertOrg checkout my work and assign this to me.

**Comment by theExpertOrg** [comment]
i assign this to @ajayexists

**Comment by ajayfounds** [comment]
i can do this

**Comment by theExpertOrg** [comment]
okayy ... then,  show me if i like your work .... i will merge your pr
