### ISSUE TITLE
Add JavaScript file in the calculator app.

### ISSUE THREAD

**Issue by theExpertOrg** [theExpertOrg/Project_Expert#3]
Add JavaScript file in the calculator app, that it works properly.

**Comment by sulavghimiree** [comment]
@theExpertOrg I will do it. Please assign me this...

**Comment by Virtual4087** [comment]
assign me this

**Comment by ghost** [comment]
checkout my projects  and assign to this project to me.

**Comment by theExpertOrg** [comment]
i will assign this to you @ajayexists  hope u complete it well.

**Comment by Virtual4087** [comment]
I already opened a pr, check it once and add it if you like it.

**Comment by ajayfounds** [comment]
give me a chance to do this.

**Comment by theExpertOrg** [comment]
i give it to u @ajayfounds
