### ISSUE TITLE
correct the JS file of Login form

### ISSUE THREAD

**Issue by theExpertOrg** [theExpertOrg/Project_Expert#4]
JS file is incomplete. make it complete so that the form will work properly

**Comment by ghost** [comment]
please assign this to me . checkout my other works on your repository.

**Comment by theExpertOrg** [comment]
okay... i will assign it to you @ajayexists

**Comment by Pariharx7** [comment]
Can you assign me this issue @theExpertOrg ?

**Comment by ajayfounds** [comment]
js file for login page . I can do it . Please assign this to me

**Comment by theExpertOrg** [comment]
i aasign this to u @ajayfounds
